[package]
edition = "2021"
name = "skill-check"
version = "0.1.0"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[dev-dependencies]
cargo-watch = "8.4.0"
tempfile = "3.3"

[profile.dev]
